use_frameworks!

target 'CQAssetsDisplay_Example' do
  pod 'CQAssetsDisplay', :path => '../'
  pod 'CQVRPlayer', :path => '../../CQVRPlayer'

  target 'CQAssetsDisplay_Tests' do
    inherit! :search_paths

    
  end
end
