inhibit_all_warnings!
use_frameworks!
platform :ios, '8.0'

target 'CQAssetsDisplay_Example' do
  pod 'CQAssetsDisplay', :path => '../'
  pod 'CQVRPlayer', :path => '../../CQVRPlayer'

  target 'CQAssetsDisplay_Tests' do
    inherit! :search_paths

    
  end
end
