inhibit_all_warnings!
use_frameworks!
platform :ios, '8.0'

target 'CQAssetsDisplay_Example' do
    pod 'CQVRPlayer', :path => '../../CQVRPlayer'
    pod 'CQAssetsDisplay', :path => '../'

  target 'CQAssetsDisplay_Tests' do
    inherit! :search_paths

    
  end
end
